# Generated by Django 4.2 on 2023-04-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_fa_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='qrcode',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
