# Generated by Django 4.2 on 2023-09-25 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_fa_app', '0002_remove_user_otp_enabled_remove_user_otp_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_expiry_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
